---
- name: Apache Config Playbook
  hosts: localhost
  connection: local
  become: false  
  tasks:
    - name: Copy vhost file
      ansible.builtin.copy:
        src: custom_vhost.conf
        dest: ./custom_vhost_deployed.conf 
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      ansible.builtin.debug:
        msg: "SUCCESS: Handler triggered because the file was copied!"